project_id = "ykhmoelrzqgxrgrsehat"

[functions.check-maintenance-schedule]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.bulkfollows-services]
verify_jwt = true

[functions.bulkfollows-order]
verify_jwt = true

[functions.bulkfollows-status]
verify_jwt = true

[functions.translate-service]
verify_jwt = true
