project_id = "ykhmoelrzqgxrgrsehat"

[functions.check-maintenance-schedule]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.translate-service]
verify_jwt = true

[functions.user-api]
verify_jwt = false

[functions.check-refills]
verify_jwt = true

[functions.provider-services]
verify_jwt = true

[functions.provider-balance]
verify_jwt = true

[functions.provider-order]
verify_jwt = true

[functions.sync-orders-status]
verify_jwt = true

[functions.paylink-payment]
verify_jwt = false

[functions.get-exchange-rate]
verify_jwt = false

[functions.tamara-payment]
verify_jwt = false

[functions.get-order-provider-status]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.admin-notify]
verify_jwt = false

[functions.notify-order-status]
verify_jwt = false

[functions.notify-deposit-success]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.weekly-admin-report]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.social-oembed]
verify_jwt = false

[functions.financing-notification]
verify_jwt = false

[functions.career-notification]
verify_jwt = false
