-- Rollback point for security hardening batch 1 (2026-10-03). Restores the exact previous rules if needed.
DROP POLICY IF EXISTS "System manages rate limits" ON public.rate_limit_records;
CREATE POLICY "System can manage rate limits" ON public.rate_limit_records FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "System reads blacklists" ON public.fraud_blacklists;
CREATE POLICY "System can read blacklists" ON public.fraud_blacklists FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Admins or owner insert notifications" ON public.notifications;
CREATE POLICY "System can insert notifications" ON public.notifications FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Admins or self insert audit logs" ON public.audit_logs;
CREATE POLICY "Anyone can insert audit logs" ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Owner or admin view ticket attachments" ON storage.objects;
CREATE POLICY "Anyone can view ticket attachments" ON storage.objects FOR SELECT TO public USING (bucket_id = 'ticket-attachments');
DROP POLICY IF EXISTS "Signed-in users can view settings" ON public.financing_settings;
CREATE POLICY "Anyone can view settings" ON public.financing_settings FOR SELECT TO public USING (true);
CREATE POLICY "Admins can view all admin notifications" ON public.admin_notifications FOR SELECT TO public USING (true);
CREATE POLICY "Admins can update admin notifications" ON public.admin_notifications FOR UPDATE TO public USING (true);
CREATE POLICY "Admins can delete admin notifications" ON public.admin_notifications FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS "Signed-in users insert admin notifications" ON public.admin_notifications;
CREATE POLICY "System can insert admin notifications" ON public.admin_notifications FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "System inserts fingerprints" ON public.device_fingerprints;
CREATE POLICY "System can insert fingerprints" ON public.device_fingerprints FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "System inserts fraud signals" ON public.fraud_signals;
CREATE POLICY "System can insert fraud signals" ON public.fraud_signals FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Self insert verification audit logs" ON public.verification_audit_logs;
CREATE POLICY "Anyone can insert verification audit logs" ON public.verification_audit_logs FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "System inserts service credits" ON public.service_credits;
DROP POLICY IF EXISTS "System updates service credits" ON public.service_credits;
CREATE POLICY "System can insert service credits" ON public.service_credits FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "System can update service credits" ON public.service_credits FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS "System inserts credit transactions" ON public.service_credit_transactions;
CREATE POLICY "System can insert credit transactions" ON public.service_credit_transactions FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "System inserts credit reviews" ON public.service_credit_reviews;
CREATE POLICY "System can insert credit reviews" ON public.service_credit_reviews FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "System inserts deposit ledger" ON public.financing_deposit_ledger;
DROP POLICY IF EXISTS "System updates deposit ledger" ON public.financing_deposit_ledger;
CREATE POLICY "Service role can insert deposit ledger" ON public.financing_deposit_ledger FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Service role can update deposit ledger" ON public.financing_deposit_ledger FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS "System manages transfers" ON public.internal_transfers;
CREATE POLICY "Service role can manage transfers" ON public.internal_transfers FOR ALL TO public USING (true) WITH CHECK (true);
-- Function execute rights: previously granted to PUBLIC (anon + authenticated). Re-grant with:
-- GRANT EXECUTE ON FUNCTION public.<name>(<args>) TO PUBLIC;
