import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export type HostingProductType = 'droplet' | 'database' | 'spaces' | 'app_platform' | 'load_balancer' | 'kubernetes' | 'firewall';

export interface HostingProduct {
  id: string;
  product_type: HostingProductType;
  name: string;
  name_ar: string;
  description: string | null;
  description_ar: string | null;
  specs: Record<string, any>;
  do_price: number;
  our_price: number;
  billing_period: 'hourly' | 'monthly' | 'yearly';
  is_active: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface HostingOrder {
  id: string;
  order_number: string;
  user_id: string;
  product_id: string | null;
  product_type: string;
  do_resource_id: string | null;
  do_resource_name: string | null;
  do_region: string | null;
  do_size: string | null;
  do_image: string | null;
  configuration: Record<string, any>;
  do_price: number;
  our_price: number;
  status: 'pending' | 'provisioning' | 'active' | 'suspended' | 'terminated' | 'failed';
  provisioned_at: string | null;
  expires_at: string | null;
  admin_notes: string | null;
  created_at: string;
  updated_at: string;
  product?: HostingProduct;
}

export const useHostingProducts = (productType?: HostingProductType) => {
  return useQuery({
    queryKey: ['hosting-products', productType],
    queryFn: async () => {
      let query = supabase
        .from('hosting_products')
        .select('*')
        .eq('is_active', true)
        .order('display_order', { ascending: true });

      if (productType) {
        query = query.eq('product_type', productType);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as HostingProduct[];
    },
  });
};

export const useAllHostingProducts = () => {
  return useQuery({
    queryKey: ['all-hosting-products'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('hosting_products')
        .select('*')
        .order('product_type', { ascending: true })
        .order('display_order', { ascending: true });

      if (error) throw error;
      return data as HostingProduct[];
    },
  });
};

export const useHostingOrders = (userId?: string) => {
  return useQuery({
    queryKey: ['hosting-orders', userId],
    queryFn: async () => {
      let query = supabase
        .from('hosting_orders')
        .select(`
          *,
          product:hosting_products(*)
        `)
        .order('created_at', { ascending: false });

      if (userId) {
        query = query.eq('user_id', userId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as HostingOrder[];
    },
  });
};

export const useCreateHostingOrder = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (orderData: {
      product_id: string;
      product_type: string;
      configuration: Record<string, any>;
      do_price: number;
      our_price: number;
      do_region?: string;
      do_size?: string;
      do_image?: string;
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('يجب تسجيل الدخول أولاً');

      const { data, error } = await supabase
        .from('hosting_orders')
        .insert({
          user_id: user.id,
          product_id: orderData.product_id,
          product_type: orderData.product_type,
          configuration: orderData.configuration,
          do_price: orderData.do_price,
          our_price: orderData.our_price,
          do_region: orderData.do_region || null,
          do_size: orderData.do_size || null,
          do_image: orderData.do_image || null,
          order_number: '', // Auto-generated by trigger
        } as any)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['hosting-orders'] });
      toast.success('تم إنشاء الطلب بنجاح');
    },
    onError: (error: any) => {
      toast.error(error.message || 'حدث خطأ أثناء إنشاء الطلب');
    },
  });
};

export const useUpdateHostingProduct = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...updates }: Partial<HostingProduct> & { id: string }) => {
      const { data, error } = await supabase
        .from('hosting_products')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['hosting-products'] });
      queryClient.invalidateQueries({ queryKey: ['all-hosting-products'] });
      toast.success('تم تحديث المنتج بنجاح');
    },
    onError: (error: any) => {
      toast.error(error.message || 'حدث خطأ أثناء التحديث');
    },
  });
};

export const useDigitalOceanAPI = () => {
  return useMutation({
    mutationFn: async ({ action, data }: { action: string; data?: any }) => {
      const response = await supabase.functions.invoke('digitalocean-api', {
        body: { action, data },
      });

      if (response.error) throw response.error;
      if (!response.data.success) throw new Error(response.data.error);
      
      return response.data.data;
    },
  });
};
